### ISSUE TITLE
Compose a Formal Announcement for Upstream

### ISSUE THREAD

**Issue by RandomDSdevel** [portage-brew/portage-brew-staging-and-evolution#12]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We need to publicize ourselves somewhat better, but I'm having trouble thinking of something to use for that purpose that remains in the spirit of #11 at the moment due to…remaining distaste over how affairs were handled upstream that I'm still processing.  I'm thus leaving this issue open for idea submissions, wording proposals, and rough drafts (either as comments here or PRs to close this issue.)  

CC:  
- @blogabe (Since I've seen you doing marketing and you might therefore have an opinion here.)  
- @portage-brew/maintainers in general.

**Comment by blogabe** [comment]
@RandomDSdevel Happy to help where and how I can, Bryce.  About to post to the discourse site that the conversation has shifted to and at the very least alert others affected to this tap.  Marketing this to build a critical mass would be easier with a push from the HB team but they seem resistant due to the concern that it comes off as an official endorsement.  Looks like we'll have to go it on our own.

**Comment by RandomDSdevel** [comment]
@blogabe:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yeah, I was thinking Discourse would be a good place to start.  Comment here with a link to what you post, and then you can close this issue.

**Comment by blogabe** [comment]
https://discourse.brew.sh/t/maintaining-a-tap-to-provide-options-for-a-formula/3871/25?u=blogabe

**Comment by RandomDSdevel** [comment]
@blogabe:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I was thinking more of doing it in a new thread, but thanks!
