### ISSUE TITLE
Confirm How to Proceed

### ISSUE THREAD

**Issue by RandomDSdevel** [portage-brew/portage-brew-staging-and-evolution#2]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Should anything developed here end up being a Homebrew fork, or should we start with something else?

**Comment by blogabe** [comment]
I think a long term strategy to get re-introduced back into Homebrew is key.  A fork maybe makes the most sense.  Effectively a centralized tap for formulae allowing for source compilation and to include options.  Maybe down the line, HB can bring it back in line like like Cask (understanding that Cask was always independent).

**Comment by RandomDSdevel** [comment]
@blogabe:  

> I think a long term strategy to get re-introduced back into Homebrew is key. …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Keeping as many commits upstreamed as possible would be ideal, at the very least.  

> …A fork maybe makes the most sense. Effectively a centralized tap for formulae allowing for source compilation and to include options. …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#4 heavily implies more than just an independently maintained tap is needed here…  

> …Maybe down the line, HB can bring it back in line like like Cask (understanding that Cask was always independent).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Upstream's recent historical trends and emergent attitude with respect to handling builds from source makes that appear seem somewhat unlikely to me, but keeping a weather eye on the situation wouldn't hurt.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@rw suggests looking at [the Nix package manager](https://nixos.org/nix/) in #5.  However, although migrating to another package manager entirely is certainly possible, making doing so the guidance produced by this project would:  

- not result in something that users of Homebrew as it currently stands could easily migrate to without additional tooling (though we could likely provide this if we felt it was needed)
- defeat the point/purpose of staging something here to eventually upstream back into Homebrew, a goal initially made explicit by @blogabe's [earlier comment](https://github.com/portage-brew/portage-brew/issues/2#issuecomment-453310887).  

We might undoubtedly investigate taking some inspiration form Nix or other package-management alternatives besides Homebrew in further developing a fork of it, but I wouldn't initially want that to take undue priority over making obvious improvements to this fork of the '`brew`' codebase of ours (once it's instantiated, of course.)

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Never mind; @rw wanted to add documentation for the possible consideration of forays in such directions to the read-me, starting with some about Nix.  Discussion of that will resume back in the other issue thread.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Since nobody seems to have any objections, I'm going to go ahead and create the fork.  

(Update:  It's at, reasonably enough, [portage-brew/brew](https://github.com/portage-brew/brew).)

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@rw has at least one initial thought on what we could do with our Homebrew fork in #6.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now that we're moving forward with a Homebrew fork, I'm closing this issue.  Feel free to add more comments if you have any concerns with this direction, however.

**Comment by blogabe** [comment]
In case you haven't seen this discussion in Homebrew's discourse thread: https://discourse.brew.sh/t/maintaining-a-tap-to-provide-options-for-a-formula/3871

Seems a few others have been caught unaware of these changes to remove all options from formulae.  The HB team has pushed the host the formula on your own personal tap option.  I still feel like a centralized tap makes more sense that having many people create their own taps to possibly include multiple variations of similar formulae.

The challenge right now is making the people this impacts aware of the issue and secondly, to make them aware of this project that may help/alleviate the issue.

To be sure there are many other issues to resolve as well... such as now keeping two formula up to date: the official homebrew one w/ no options and a secondary version on this tap allowing for options.

**Comment by RandomDSdevel** [comment]
@blogabe:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Thanks for that thread, I'll read through it.  I've invited @saagarjha and @joshka to join us here both as a general member of the portage-brew organization and as a member of [our 'Core Collaborators' team](https://github.com/orgs/portage-brew/teams/core-collaborators).  ~~(Addendum via edit:  I'll also do that for other candidate users from that thread as I see them.)~~  (Addendum 3 via edit:  Never mind, I've seen all of them and also added them to the list earlier in this post.)  (Addendum 2 via edit:  I'll also add them to other teams and make them organization owners as needed.)  I'm still wary of how open dissent on the issues we all feel are important here might be taken upstream, though, so I'm personally going to avoid advertising ourselves outside of inviting others to join us here for now.  (Let me know if you find anyone willing enough to brave _that_ possible storm…&thinsp;—&thinsp;I might join in later, but the thought of _starting_ it still makes me somewhat hesitant at the moment.)

**Comment by saagarjha** [comment]
> Seems a few others have been caught unaware of these changes to remove all options from formulae. The HB team has pushed the host the formula on your own personal tap option. I still feel like a centralized tap makes more sense that having many people create their own taps to possibly include multiple variations of similar formulae.

You've pretty much hit the nail on the head: I started that thread because I was unaware of the removal of options and was looking to foster discussion as to how to diminish the impact of this change, and I've pretty much come to the same conclusion as you: I'm disappointed with the way this was handled, and disillusioned with the direction Homebrew is moving in. The day that thread was closed, I gave up and got rid Homebrew, installed MacPorts, and have been using it since as the replacement. Sure, it's a compromise in some aspects, but I'm quite happy with the results and find the project to be much nicer in its design. Keeping that in mind, I'd be glad to support your project–I'm not against improving Homebrew, though it would take quite a few changes for me to want to switch back–but I thought I'd just let you know that my current direction is away from what Homebrew is doing right now.

> I'm still wary of how open dissent on the issues we all feel are important here might be taken upstream, though, so I'm personally going to avoid advertising ourselves outside of inviting others to join us here for now. (Let me know if you find anyone willing enough to brave that possible storm… — I might join in later, but the thought of starting it still makes me somewhat hesitant at the moment.)

Ha, I know firsthand how this can end up. I'm basically done with the project at this point, so I'm planning on writing up a thing as to what I felt was wrong with Homebrew and why I switched. If nothing else, you might find it useful as a way of comparing your project's goals with what I'm looking for in a package manager, though, considering that I had used Homebrew for so long, I'm sure you can see that I'm not very picky ;)

**Comment by joshka** [comment]
Hey,
I have a somewhat different take on this. My objection was really to how this was delivered to the end user. It's generally not OK with me to change something like this without first notifying that it's going to change. I used some rather strong language in that thread, to call out that the way that this was handled was not OK. That said, I'm not sure whether this is the right approach to solving some of the issues of homebrew. I really do understand the motivations for what the homebrew maintainers are doing here. Their problem is allocation of time, and their solution was to cut features to achieve that. I'm uncertain whether forking homebrew would help that, and I can forsee a future where the same trade offs have to be considered for this.

I appreciate the invitation to help with this, but I'm much more inclined to continue helping with the homebrew project rather than this new one.

>I'm still wary of how open dissent on the issues we all feel are important here might be taken upstream, though.

A suggestion for this. Don't treat this as a war or an argument that needs to be won about the features that are missing / different to how you want them. Treat this more as an experiment to prove that the things that you care about are useful, possible, impactful, etc. Find ways to provide rationale for the things where you differ rather and the open dissent should be acceptable to rational people. An interesting example of this approach I read just today was [Fossil vs Git](https://fossil-scm.org/fossil/doc/trunk/www/fossil-v-git.wiki) on Fossil's wiki. The thing I really liked about this article is that it presented the differences with emapthy for the underlying reasons that lead to Git's choices and doesn't take a stance that Fossil's choices are the only right way. The resulting conversation about this on hackernews was therefore pretty civil compared to had this been a 'Why Fossil is better than Git' type article.

**Comment by RandomDSdevel** [comment]
@joshka:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Thank you for your feedback, perspective, and advice.  I agree that discourse regarding procedural disputes started out as somewhat more heated and emotionally charged than was/is rational, even given the reactions to how upstream changes were prepared, handled, and announced.  I've created [a new issue](https://github.com/portage-brew/portage-brew-staging-and-evolution/issues/11) to track the creation of a document outlining the kind of discussion you've referenced.  As for concerns related to managing time and codebase size, we know of an existing, successful [example](https://github.com/portage-brew/portage-brew-staging-and-evolution/issues/4#issuecomment-457609331) of another user privately maintaining something like what we're preparing here and may be able to take some lessons from it if they choose to make their work public or rediscover them independently.

**Comment by joshka** [comment]
Oh and I meant to say, regardless of my thoughts, good luck with this. I will be more than happy to be shown to be wrong about the problems I predicted above. They certainly aren't insurmountable. I bring them up only as they seem that way to me. I applaud you for taking on this challenge regardless.
